### ISSUE TITLE
I will be appreciated to answer my question about the entire system

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#40]
please answer my questions:
1.How i can obtain bandwidth each Access point in controller, like calculate performance of Access point and show in controller to choose which access point are free to handle more client.?

2.How each method in odinagent.cc called in odinmaster.java , how they are connected, how i can write function and call it in controller? (how can i write program in  AP).?

3.I want remove some Client for policy. just moment , like editing RTS/CTS (Request to Send / Clear to Send)  in Access points. When client want to send packets, controller don't let any message received or send from this client for some second without remove it. ?

**Comment by josemariasaldana** [comment]
Q1.How i can obtain bandwidth each Access point in controller, like calculate performance of Access point and show in controller to choose which access point are free to handle more client.?

A1. We have developed an application "Showstatistics" in the controller. You can do something similar. We have not yet integrated statistics and decisions. New applications combining them could be written.
https://github.com/Wi5/odin-wi5/wiki/Applications-available-in-the-controller

Q2. How each method in odinagent.cc called in odinmaster.java , how they are connected, how i can write function and call it in controller? (how can i write program in AP).?

A2. You have to follow the existing examples. In order to do something new in the controller, you have to add new applications. If you want to ask new questions to the AP, you will have to add new handlers and new code in odinagent.cc and odinagent.hh (https://github.com/Wi5/odin-wi5-agent/tree/master/src)

Q3.I want remove some Client for policy. just moment , like editing RTS/CTS (Request to Send / Clear to Send) in Access points. When client want to send packets, controller don't let any message received or send from this client for some second without remove it. ?

A3. This would be a new application. See A2.
