### ISSUE TITLE
Issue with Odin SSID

### ISSUE THREAD

**Issue by fouadyousufdar** [Wi5/odin-wi5#9]
Hi @josemariasaldana 
i have been trying to make this project running. i followed your mentioned steps without facing error but the ODIN ssid doesn't appear on the STA after completing all the configurations.
i am using Netgear 3700v4 router as AP. My Controller shows that OVS switch is connected but later no SSID of ODIN appears. Kindly suggest a solution.Thank You.

**Comment by josemariasaldana** [comment]
Hi,

Have you patched the driver? Currently Odin only has a patch for the ath9k driver. I don't know if your router has this driver. https://wiki.openwrt.org/toh/netgear/wndr3700.

We are building a wiki in order to share all our experiences (https://github.com/Wi5/odin-wi5/wiki). We will add more info in the following days.

**Comment by fouadyousufdar** [comment]
Hi @josemariasaldana 

Thank you for the reply.
My router has ath9k based wifi card and i have patched it with the provided patch file.
i may have issue in building click for openwrt. kindly guide me about the click build.

Regards;
FYD

**Comment by josemariasaldana** [comment]
Hi, Fouad. We are finishing the wiki, but it is not ready yet. In the meantime, I have sent you by e-mail some files with instructions.
